# Generated by Django 3.0.8 on 2020-10-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'saldo',
            },
        ),
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debito', models.DecimalField(decimal_places=2, max_digits=19)),
                ('credito', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                'db_table': 'transacoes',
            },
        ),
    ]
