# Generated by Django 3.0.8 on 2020-10-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saldo',
        ),
    ]
