# Generated by Django 3.1.2 on 2020-10-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                'db_table': 'saldo',
            },
        ),
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debito', models.DecimalField(decimal_places=2, max_digits=19)),
                ('credito', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                'db_table': 'transacoes',
            },
        ),
        migrations.RemoveField(
            model_name='member',
            name='band',
        ),
        migrations.RemoveField(
            model_name='music',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Band',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Music',
        ),
    ]
