# Generated by Django 3.1.2 on 2020-10-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201008_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saldo',
            name='saldo',
        ),
    ]
