# Generated by Django 3.0.8 on 2020-10-11 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacoes',
            name='descricao_credito',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transacoes',
            name='descricao_debito',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
