# Generated by Django 3.0.8 on 2020-10-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_saldo_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacoes',
            name='saldo_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
